version: "3.7"
services:
  polyserv:
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${DEV_REPL_PORT}:16969
      - ${DEV_APP_PORT}:6969
    volumes:
      - ./runtime_data:/app/runtime_data
      - ./deps.edn:/app/deps.edn
      - ./workspace.edn:/app/workspace.edn
      - ./bases:/app/bases
      - ./components:/app/components
      - ./development:/app/development
      - ./projects:/app/projects
    command: [ "clj",  "-M:dev:test:nrepl" ]
  mongo:
    image: mongo:5.0.17
    ports:
      - ${DEV_MONGO_PORT}:27017
    volumes:
      - ./runtime_data/mongo:/data/db
  redis:
    image: redis:7.0.11
    ports:
      - ${DEV_REDIS_PORT}:6379
